export ta=$HOME/ta

# Hook up homebrew
PATH="$PATH:$HOME/.local/bin"
eval "$(/opt/homebrew/bin/brew shellenv)"

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

# Use gnu find utils instead of mac equivalents. This is needed to use the right version of find in neovim plugins
PATH=$(brew --prefix)/opt/findutils/libexec/gnubin:$PATH

# Add java to path
PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# Add bin to path
[[ -d $HOME/bin ]] || mkdir $HOME/bin
PATH="$HOME/bin:$PATH"

# Aliases
alias e='XDG_DATA_HOME="$HOME/.nvim/data" XDG_CONFIG_HOME="$HOME/.nvim/config" JDTLS_JVM_ARGS="-javaagent:$XDG_DATA_HOME/nvim/mason/packages/jdtls/lombok.jar" nvim'
alias g=git

# Use vi mode in shell
set -o vi

# easy navigation to common folders
setopt auto_cd
for directory in $(ls -d $ta/*/dev); do
  cdpath+=($directory)
done

# Use nvim as editor
export EDITOR=nvim

# Use ctrl-r to search for command in shell history
bindkey '^R' history-incremental-search-backward

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

config_directories=($(echo $ta/*))
for directory in $config_directories; do
  # Add scripts to path
  for file in $(find $directory/scripts -type file); do
    ln -sf $file $HOME/bin/$(basename $file)
  done

  # load specific zshrc
  [[ -f $directory/.zshrc ]] && source $directory/.zshrc

  # Generate ssh-config
  ssh_config=$HOME/.ssh/config
  for file in $directory/ssh-config; do
    [[ -z $(cat $ssh_config 2> /dev/null | grep $file) ]] && echo Include $file >> $HOME/.ssh/config
  done 2> /dev/null
done
