#! /bin/sh

function randomchar {
  chars=("1" "2" "3" "4" "5" "6" "7" "8" "9" "0" "!" "@" "#" "$" "%" "^" "&" "*" "[" "}" "-" "_" "]" "{" "+")
  size=${#chars[@]}
  index=$(($RANDOM % $size + 1))
  echo ${chars[$index]}
}

password=$(randomchar)

words=$(sort -R /usr/share/dict/words | head -n 4)
for word in $words; do
  password+="${word:u}$(randomchar)"
done

echo "$password"
