#! /bin/sh

name=$1
key=$2

[[ -z $key ]] && "echo usage: secret <name> <key>" && exit 1

[[ $key = "password" ]] && echo $(pass $name | head -n 1) && exit 0
echo $(pass $name | rg -i $key | cut -d ' ' -f 2)
